language: node_js
node_js:
  - 12
jobs:
  include:
    - stage: test
      script: npm test
    - stage: deploy storybook
      script: npm run deploy-storybook -- --ci
      if: branch = master
stages:
  - test
  - name: deploy storybook
